export const info = {
    title: "Gateway Academic",
    logoUrl: "/logo.png",
    description: "Institución educativa que transforma vidas a través de programas de inglés y certificaciones internacionales.",
    keywords: "Educación, Inglés, Certificaciones, Gateway Academic, Programas de Inglés, Cambridge, TOEFL, IELTS",
    promoImages :['/promo1.jpg', '/promo2.jpg', '/promo3.jpg'],
    socialMediaLinks: {
        facebook: "https://www.facebook.com/GatewayCorporation",
        instagram: "https://www.instagram.com/gatewaycorporation.ec",
        linkedin: "https://www.linkedin.com/company/gatewayacademic",
        tiktok: "https://www.tiktok.com/@gatewayacademic",
    },
    contactEmail: "gatewaycorporation@hotmail.com",
    contactPhone: "+593 958828414",
    whatsAppNumber: 593958828414,
    address: "Matriz: Miguel Oviedo 5-50 y Antonio José de Sucre EC100105 Ibarra, Ecuador",
    city: "Ibarra",
    state: "Imbabura",
    country: "Ecuador",
    operatingHoursDetails: {
        weekdays: "8:00 AM - 6:30 PM",
        saturdays: "Sábados: 9:00 AM - 1:00 PM",
        sundays: "Domingos: Cerrado",
    },
    footerText: "© 2024 Gateway Academic. Todos los derechos reservados.",
    googleMapLink: "https://www.google.com/maps/dir/?api=1&destination=0.3497122865869%2C-78.117164969444",
}